name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.2', '8.3' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP and Test
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:2
      - run: make app-install
      - run: make app-composer-check
      - run: make app-cs-check
      - run: make app-security-check
      - run: make app-test-with-code-coverage
      - run: make app-static-analysis