name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up PHP and Test
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:2
      - run: echo bonjour